language: python
python:
    - "3.6"

install:
  - pip install coverage twine pytest
  - "pip install -e ."

script:
  - pytest

after_success:
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      python setup.py sdist bdist_wheel ;
      twine upload dist/* ;
    fi
